### ISSUE TITLE
Отправка сообщений не работает без random_id

### ISSUE THREAD

**Issue by lehmn** [AppLoidx/VkLongPollBot#1]
При последней версии longpoll в консоль вылетает `vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: random_id is a required parameter`

**Comment by AppLoidx** [comment]
![image](https://user-images.githubusercontent.com/32590754/63211880-42873f80-c138-11e9-9252-0b0cb0b8a680.png)
Да, начиная с версии 5.90
